#!/bin/sh
set -eu
CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/vfd/terminal.toml"
if [ "$#" -eq 0 ]; then
    exec env VFDTERM=1 alacritty --class vfdterm,vfdterm --title Terminal --config-file "$CONFIG" -e fish
fi
exec env VFDTERM=1 alacritty --class vfdterm,vfdterm --title Terminal --config-file "$CONFIG" -e "$@"
