[wallpaper]
# Change this to your GIF. ~ is expanded.
file = ~/Pictures/wallpapers/lain.gif

# fill | fit | stretch | center
scaling = fill

# Caps very fast GIFs to reduce CPU/GPU use.
fps-cap = 30
paused = false
