#define _POSIX_C_SOURCE 200809L
#include <vfd/ipc.h>
#include <sys/socket.h>
#include <sys/un.h>
#include <sys/poll.h>
#include <signal.h>
#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <sys/stat.h>
#include <limits.h>
#define MAX_EVENTS 32
#define EVENT_TEXT 192
typedef struct { unsigned id; time_t when; char app[64]; char summary[EVENT_TEXT]; char body[EVENT_TEXT]; } Event;
static volatile sig_atomic_t run=1; static char theme_name[64]="lain"; static Event events[MAX_EVENTS]; static size_t event_count=0; static size_t unread_count=0; static unsigned next_event_id=1; static void stop(int s){(void)s;run=0;}
static void clean_field(char *s){for(;*s;s++)if(*s=='\n'||*s=='\r'||*s=='\t')*s=' ';}
static void event_add(const char *app,const char *summary,const char *body){Event e={0};e.id=next_event_id++;e.when=time(NULL);snprintf(e.app,sizeof e.app,"%s",app&&*app?app:"SYSTEM");snprintf(e.summary,sizeof e.summary,"%s",summary&&*summary?summary:"Notification");snprintf(e.body,sizeof e.body,"%s",body?body:"");clean_field(e.app);clean_field(e.summary);clean_field(e.body);if(event_count<MAX_EVENTS)events[event_count++]=e;else{memmove(events,events+1,sizeof events[0]*(MAX_EVENTS-1));events[MAX_EVENTS-1]=e;}unread_count++;}
static void event_list(char *out,size_t n){size_t used=0;for(size_t i=event_count;i>0;i--){Event *e=&events[i-1];struct tm tmv=*localtime(&e->when);char t[16];strftime(t,sizeof t,"%H:%M:%S",&tmv);int w=snprintf(out+used,n-used,"%u\t%s\t%s\t%s\t%s\n",e->id,t,e->app,e->summary,e->body);if(w<0||(size_t)w>=n-used)break;used+=(size_t)w;}if(!used)snprintf(out,n,"EMPTY\n");}
static void config_path(char*out,size_t n){const char*h=getenv("HOME");snprintf(out,n,"%s/.config/vfd/config.ini",h?h:"");}
static void load_theme(void){char p[PATH_MAX],line[256];config_path(p,sizeof p);FILE*f=fopen(p,"r");if(!f)return;while(fgets(line,sizeof line,f)){if(sscanf(line,"theme = %63s",theme_name)==1||sscanf(line,"theme=%63s",theme_name)==1)break;}fclose(f);}
static void save_theme(void){char dir[PATH_MAX],p[PATH_MAX];const char*h=getenv("HOME");snprintf(dir,sizeof dir,"%s/.config/vfd",h?h:"");mkdir(dir,0700);config_path(p,sizeof p);FILE*f=fopen(p,"w");if(f){fprintf(f,"[general]\ntheme = %s\n",theme_name);fclose(f);}}
static int cpu(void){static unsigned long long pi,pt;FILE*f=fopen("/proc/stat","r");unsigned long long u,n,s,i,iw,irq,si,st;if(!f)return 0;fscanf(f,"cpu %llu %llu %llu %llu %llu %llu %llu %llu",&u,&n,&s,&i,&iw,&irq,&si,&st);fclose(f);unsigned long long idle=i+iw,total=u+n+s+i+iw+irq+si+st,dt=total-pt,di=idle-pi;pt=total;pi=idle;return dt?(int)(100*(dt-di)/dt):0;}
static int mem(void){FILE*f=fopen("/proc/meminfo","r");char k[64];long v,total=0,avail=0;while(f&&fscanf(f,"%63s %ld kB",k,&v)==2){if(!strcmp(k,"MemTotal:"))total=v;else if(!strcmp(k,"MemAvailable:"))avail=v;}if(f)fclose(f);return total?(int)(100*(total-avail)/total):0;}
static int bat(char*st,size_t n){char path[128];FILE*f=NULL;int b=-1;for(int i=0;i<4&&!f;i++){snprintf(path,sizeof path,"/sys/class/power_supply/BAT%d/capacity",i);f=fopen(path,"r");}if(f){fscanf(f,"%d",&b);fclose(f);char *slash=strrchr(path,'/');if(slash)snprintf(slash+1,(size_t)(path+sizeof path-(slash+1)),"status");f=fopen(path,"r");}if(f){fgets(st,n,f);st[strcspn(st,"\n")]=0;fclose(f);}else snprintf(st,n,"Unknown");return b;}
static void reply(int fd,const char*q){char out[1024],bs[64],clock[64];time_t now=time(NULL);strftime(clock,sizeof clock,"%Y.%m.%d // %H:%M:%S",localtime(&now));int c=cpu(),m=mem(),b=bat(bs,sizeof bs);if(!strncmp(q,"GET ",4)){const char*k=q+4;if(!strcmp(k,"cpu"))snprintf(out,sizeof out,"%d\n",c);else if(!strcmp(k,"memory"))snprintf(out,sizeof out,"%d\n",m);else if(!strcmp(k,"battery"))snprintf(out,sizeof out,"%d\n",b);else if(!strcmp(k,"clock"))snprintf(out,sizeof out,"%s\n",clock);else if(!strcmp(k,"theme"))snprintf(out,sizeof out,"%s\n",theme_name);else snprintf(out,sizeof out,"ERR unknown-key\n");}else if(!strcmp(q,"SNAPSHOT")){snprintf(out,sizeof out,"theme=%s\ncpu=%d\nmemory=%d\nbattery=%d\nbattery.status=%s\nclock=%s\nevents.unread=%zu\n",theme_name,c,m,b,bs,clock,unread_count);}else if(!strncmp(q,"THEME ",6)){const char*n=q+6;if(!*n||strchr(n,'/'))snprintf(out,sizeof out,"ERR invalid-theme\n");else{snprintf(theme_name,sizeof theme_name,"%s",n);save_theme();snprintf(out,sizeof out,"OK theme=%s\n",theme_name);}}else if(!strncmp(q,"EVENT ADD\t",10)){char tmp[768];snprintf(tmp,sizeof tmp,"%s",q+10);char *app=strtok(tmp,"\t"),*summary=strtok(NULL,"\t"),*body=strtok(NULL,"");event_add(app,summary,body);snprintf(out,sizeof out,"OK event=%u\n",next_event_id-1);}else if(!strcmp(q,"EVENTS")){event_list(out,sizeof out);}else if(!strcmp(q,"EVENTS READ")){unread_count=0;snprintf(out,sizeof out,"OK\n");}else if(!strcmp(q,"EVENTS CLEAR")){event_count=0;unread_count=0;snprintf(out,sizeof out,"OK\n");}else if(!strcmp(q,"PING"))snprintf(out,sizeof out,"PONG\n");else if(!strcmp(q,"STATUS"))snprintf(out,sizeof out,"running=yes version=0.9.0 theme=%s events=%zu unread=%zu\n",theme_name,event_count,unread_count);else if(!strcmp(q,"SHUTDOWN")){snprintf(out,sizeof out,"OK\n");run=0;}else snprintf(out,sizeof out,"ERR unknown-command\n");write(fd,out,strlen(out));}
int main(void){signal(SIGINT,stop);load_theme();signal(SIGTERM,stop);char p[108];if(vfd_ipc_path(p,sizeof p)){fprintf(stderr,"XDG_RUNTIME_DIR missing\n");return 1;}unlink(p);int s=socket(AF_UNIX,SOCK_STREAM,0);struct sockaddr_un a={.sun_family=AF_UNIX};snprintf(a.sun_path,sizeof a.sun_path,"%s",p);if(bind(s,(void*)&a,sizeof a)||listen(s,8)){perror("vfdd");return 1;}while(run){struct pollfd f={s,POLLIN,0};if(poll(&f,1,500)>0){int c=accept(s,NULL,NULL);if(c>=0){char q[256];ssize_t n=read(c,q,sizeof q-1);if(n>0){q[n]=0;q[strcspn(q,"\r\n")]=0;reply(c,q);}close(c);}}}close(s);unlink(p);return 0;}
